import Head from 'next/head'
import Image from 'next/image'
import { v4 as uuidv4 } from 'uuid'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

const client = axios.create({
  baseURL: "/api" 
});

export default function NewGame() {
  const handlerSubmitted = async (event:any) => {
    event.preventDefault();

    const data = {
      gameId: uuidv4(),
      user: event.target.userName.value,
      room: event.target.roomName.value
    }

    // console.log(data);
    client.post('/games', data).then((response) => {
      console.log(response.data);
    });
    
  }

  return (
    <div>
      <Head>
        <title>Planning Poker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Planning Poker</h1>
        <form onSubmit={handlerSubmitted}>
          <label htmlFor="userName">You display name</label>
          <input type="text" id="userName" name="userName" />
          <label htmlFor="roomName">Room Name</label>
          <input type="text" id="roomName" name="roomName" />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  )
}