import { Head } from "next/document";
import { FormEvent } from "react";

export default function User() {
  function handlerSubmitted (event: FormEvent<HTMLFormElement>): void {
    throw new Error("Function not implemented.");
  }

  return (
    <div>
      <Head>
        <title>Planning Poker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Planning Poker</h1>
        <form onSubmit={handlerSubmitted}>
          <label htmlFor="userName">User Name</label>
          <input type="text" id="userName" name="userName" />
          <label htmlFor="roomName">Room Name</label>
          <input type="text" id="roomName" name="roomName" />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  )
}