import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import api from '../../utils/api';

const inter = Inter({ subsets: ['latin'] })

type GameTypes = {
  gameId: string;
  user: string;
  room: string;
};

export default function Game() {

  const router = useRouter();
  const [game, setGame] = useState<GameTypes>();
  
  useEffect(() => {
    const data = {
      gameId: router.query.id,
    }
  
    api.get('/games', {
      params: {
        gameId: data.gameId
      }
    }).then((response) => {
      setGame(response.data.gamesData[0]);
    });
  }, [router]);

  return (
    <div>
      <Head>
        <title>Planning Poker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{ game ? game.room : 'nop' }'s room</h1>
        <p>...</p>
      </main>
    </div>
  )
}