import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import { Fragment } from 'react'
import { Menu, Transition } from '@headlessui/react'
import { ChevronDownIcon } from '@heroicons/react/20/solid'
import { Cog6ToothIcon } from '@heroicons/react/24/outline'

import api from '../../utils/api';

const inter = Inter({ subsets: ['latin'] })

type GameTypes = {
  gameId: string;
  user: string;
  room: string;
};

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

export default function Game() {

  const router = useRouter();
  const [game, setGame] = useState<GameTypes>();
  
  useEffect(() => {
    const data = {
      id: router.query.id,
    }

    api.get('/games/' + data.id)
      .then((response) => {
        setGame(response.data);
      });
  }, [router]);

  return (
    <div className="bg-white">
      <Head>
        <title>Planning Poker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className='HeaderMain absolute inset-x-0 top-0 z-50'>
          <nav className="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
            <div className="flex lg:flex-1">
              <a href="#" className="-m-1.5 p-1.5">
                <span className="sr-only">PlanPoker</span>
                <img
                  className="h-8 w-auto"
                  src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                  alt=""
                />
              </a>
            </div>

            <div className="flex lg:hidden">
              <button
                type="button"
                className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                onClick={() => console.log('open menu')}
              >
                <span className="sr-only">Open main menu</span>
                ...
              </button>
            </div>
            <div className="hidden lg:flex lg:gap-x-12">
              <div className="sm:col-span-3">
                <div className="mt-2">
                  <Menu as="div" className="relative inline-block text-left">
                    <div>
                      <Menu.Button
                        type="button"
                        className="inline-flex w-full justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                      >
                        { game ? game.room : 'nop' }
                        <ChevronDownIcon className="-mr-1 h-5 w-5 text-gray-400" aria-hidden="true" />
                      </Menu.Button>
                    </div>
                    <Transition
                      as={Fragment}
                      enter="transition ease-out duration-100"
                      enterFrom="transform opacity-0 scale-95"
                      enterTo="transform opacity-100 scale-100"
                      leave="transition ease-in duration-75"
                      leaveFrom="transform opacity-100 scale-100"
                      leaveTo="transform opacity-0 scale-95"
                    >
                      <Menu.Items className="absolute right-0 z-10 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                        <div className="py-1">
                          <Menu.Item>
                            {({ active }) => (
                              <a
                                href="#"
                                className={classNames(
                                  active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
                                  'block px-4 py-2 text-sm flex items-center'
                                )}
                              >
                                <Cog6ToothIcon className="-ml-1 mr-2 h-5 w-5 text-gray-400" aria-hidden="true" />
                                Game settings
                              </a>
                            )}
                          </Menu.Item>
                        </div>
                      </Menu.Items>
                    </Transition>
                  </Menu>
                </div>
              </div>
            </div>
            <div className="hidden lg:flex lg:flex-1 lg:justify-end">
              <a href="#" className="text-sm font-semibold leading-6 text-gray-900">
                Log in <span aria-hidden="true">&rarr;</span>
              </a>
            </div>
          </nav>
        </header>
        <main className="relative isolate px-6 pt-14 lg:px-8">
          <div className="mx-auto py-6 sm:px-6 lg:px-8">
            <h1>main</h1>
          </div>
        </main>
      </div>
    </div>
  )
}