import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { v4 as uuidv4 } from 'uuid'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import api from '../utils/api';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const router = useRouter()

  const handlerSubmitted = async (event:any) => {
    event.preventDefault();

    const data = {
      gameId: uuidv4(),
      room: event.target.roomName.value
    }

    api.post('/games', data).then((response: { data: any }) => {
      router.push(`/room/${response.data.id}`)
    });
  }

  return (
    <>
      <Head>
        <title>Planning Poker Open Source</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-4 grid grid-flow-row h-screen justify-stretch">
        <header className="flex justify-center items-center">
          <Image src="/logo.webp" alt="Planning Poker" width={168} height={88} />
        </header>
        <div className="grid md:grid-cols-3 gap-6 center">
          <form onSubmit={handlerSubmitted}>
            <div className="col-span-6 sm:col-span-3">
              <h2 className="text-lg font-bold py-4">Insert the room’s name</h2>
              <input
                type="text"
                id="room-name"
                name="roomName"
                placeholder="Game's name"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              />
            </div>
            <div className="py-3">
              <button
                type="submit"
                className="inline-flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              >
                Create game
              </button>
            </div>
          </form>
        </div>

      </main>
    </>
  )
}
